---
- name: Preconfig
  hosts: demo
  tasks:
    - name: Docker install
      block:
        - name: Adding universe
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present
        - name: Install additional packets
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            update-cache: yes
            cache_valid_time: 86400
        - name: Adding docker key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
        - name: Add stable repository
          apt_repository:
            repo: "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present
            update-cache: yes
            filename: docker    
        - name: Install docker-ce
          apt:
            name: docker-ce
            update-cache: yes
        - name: Check if docker installed and rebooted
          service: 
            name: docker
            state: restarted
            enabled: yes
      become: yes
    - name: Docker-compose install
      block:
        - name: Get the latest version on Docker Compose
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page
        - name: Install docker Compose
          get_url:
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-linux-x86_64"
            dest: /usr/local/bin/docker-compose
            mode: 0755
      become: yes
    - name: Installation finishing
      block:
        - name: Adding user in group Docker
          user:
            name: "{{ansible_user}}"
            groups: docker
            append: yes
        - name: Server Reboot
          reboot:
      become: yes


